import {
  IconApps,
  IconBasket,
  IconBook,
  IconCategory,
  IconCoins,
  IconCookie,
  IconDeviceGamepad2,
  IconDroplet,
  IconFlame,
  IconGasStation,
  IconGift,
  IconGlassFull,
  IconHandSanitizer,
  IconHeadphones,
  IconHeartbeat,
  IconHomeBolt,
  IconHomeCog,
  IconHomeDollar,
  IconHomeHand,
  IconHotelService,
  IconParking,
  IconPaw,
  IconPingPong,
  IconRouter,
  IconStereoGlasses,
  IconTags,
  IconTie,
  IconToolsKitchen2,
  IconTrain,
  IconTrash,
  IconUserShield,
  IconUserStar,
} from "@tabler/icons-react";

export const Icons = {
  IconApps: IconApps,
  IconBasket: IconBasket,
  IconBook: IconBook,
  IconCategory: IconCategory,
  IconCoins: IconCoins,
  IconCookie: IconCookie,
  IconDeviceGamepad2: IconDeviceGamepad2,
  IconDroplet: IconDroplet,
  IconFlame: IconFlame,
  IconGasStation: IconGasStation,
  IconGift: IconGift,
  IconGlassFull: IconGlassFull,
  IconHandSanitizer: IconHandSanitizer,
  IconHeadphones: IconHeadphones,
  IconHeartbeat: IconHeartbeat,
  IconHomeBolt: IconHomeBolt,
  IconHomeCog: IconHomeCog,
  IconHomeDollar: IconHomeDollar,
  IconHomeHand: IconHomeHand,
  IconHotelService: IconHotelService,
  IconParking: IconParking,
  IconPaw: IconPaw,
  IconPingPong: IconPingPong,
  IconRouter: IconRouter,
  IconStereoGlasses: IconStereoGlasses,
  IconTags: IconTags,
  IconTie: IconTie,
  IconToolsKitchen2: IconToolsKitchen2,
  IconTrain: IconTrain,
  IconTrash: IconTrash,
  IconUserShield: IconUserShield,
  IconUserStar: IconUserStar,
};
