export const ENDPOINTS = Object.freeze({
  login: "/api/user/login",
  register: "/api/user/register",
  budget: "/api/budget",
  expenses: "/api/expenses",
  summary: "/api/expenses/summary",
  list: "/api/expenses/list",
  cloneExpense: "/api/expenses/clone",
  userInfo: "/api/user/details",
  updateUser: "/api/user/update",
  categories: "/api/categories/get-all",
  plans: "/api/expense-plan",
  planDetails: "/api/expense-plan/details",
  downloadReport: "/api/reports",
});
